### ISSUE TITLE
Remove `dns.domain` dependancy for Kubeflow components

### ISSUE THREAD

**Issue by oginskis** [agilestacks/kubeflow-components#38]
According to our decision all hostnames of ingress-enabled components should be resolved through `ingress.hosts` parameters

**Comment by akranga** [comment]
Is this a duplication of #24 ? @oginskis feel free to reopen

**Comment by oginskis** [comment]
Yes, the list in #24 missing Kubeflow, let's keep them separate

**Comment by oginskis** [comment]
Went through all `kubeflow-*` and removed the dependency on the `dns.domain`

**Comment by akranga** [comment]
Probably have been earlier, however `git blame` suggest work on current issue. Therefore reopening this issue

```yaml
hosts:
- '${ingress.hosts}'
```

Such code is incorrect and will break kubeflow when user will decide to add one more ingress. Gateway should be converted to gotemplate and handled similar to ingresses we have in the other components... See [example](https://github.com/epam/hub-kubeflow-components/blob/develop/minio/values-ingress.yaml.gotemplate#L30)

**Comment by oginskis** [comment]
@akranga Please review and merge https://github.com/epam/hub-kubeflow-components/pull/51
