### ISSUE TITLE
Bringing components to a common standard 

### ISSUE THREAD

**Issue by NellyHargeliya** [agilestacks/kubeflow-components#53]
**1.  Create or reformat README**
 - merge: #dependencies and #requirements section of readme and use one subtitle #requirements
 - add a section TLDR with quick instructions how to add component, if any hook required as for IAM role component today, and minimum required parameters all as a snippet or snippets
So, general structure of REDME:
-- NAME COMPONENT
-- TLDR
-- Requirements
-- Parameters
-- Implementation Details
Deployment follows to the following   algorithm:
--  Inference Service config
-- See also

https://github.com/epam/hub-kubeflow-components/issues/54

**2. Standardize parameters in components according to the following list of names:**
[params.xlsx](https://github.com/epam/hub-kubeflow-components/files/12453165/params.xlsx)
**3. Check components for correct deployment**

**Comment by akranga** [comment]
@NellyHargeliya  @seseque  please advise this is a duplicate for #54 and #55? If yes, please feel free to close this issue. #54 needs to have a link to the [params.xlsx](https://github.com/epam/hub-kubeflow-components/files/12453165/params.xlsx)
