### ISSUE TITLE
Standardize parameters and README for components (part 2)

### ISSUE THREAD

**Issue by NellyHargeliya** [agilestacks/kubeflow-components#55]
The following parameters need be standardized as described https://github.com/epam/hub-kubeflow-components/issues/53 :

- [ ] [kubeflow-jupyter](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-jupyter)
- [ ] [kubeflow-katib](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-katib)
- [ ] [kubeflow-kserve](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-kserve)
- [ ] [kubeflow-metadata](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-metadata)
- [ ] [kubeflow-pipeline](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-pipeline)
- [ ] [kubeflow-profiles](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-profiles)
- [ ] [kubeflow-tensorboard](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-tensorboard)
- [ ] [kubeflow-tf-training](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-tf-training)
- [ ] [kubeflow-training-operator](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-training-operator)
- [ ] [kubeflow-volumes](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-volumes)
- [ ] [kubeflow-webhooks](https://github.com/epam/hub-kubeflow-components/tree/develop/kubeflow-webhooks)
- [ ] [mlflow](https://github.com/epam/hub-kubeflow-components/tree/develop/mlflow)
- [ ] [mysql](https://github.com/epam/hub-kubeflow-components/tree/develop/mysql)
- [ ] [nginx-ingress](https://github.com/epam/hub-kubeflow-components/tree/develop/nginx-ingress)
- [ ] [postgresql](https://github.com/epam/hub-kubeflow-components/tree/develop/postgresql)
- [ ] [s3-bucket](https://github.com/epam/hub-kubeflow-components/tree/develop/s3-bucket)
- [ ] [seldon-core](https://github.com/epam/hub-kubeflow-components/tree/develop/seldon-core)

**Comment by akranga** [comment]
@seseque  I believe this should be merged with #54 and better to be developed as part of it. Please feel free to push your updates incrementally to PR #57
